"use strict";
exports.__esModule = true;
/**
 * This module was automatically generated by `ts-interface-builder`
 */
var t = require("ts-interface-checker");
// tslint:disable:object-literal-key-quotes
exports.Link = t.iface([], {
    "text": "string",
    "title": "string",
    "url": "string"
});
exports.Author = t.iface([], {
    "name": "string",
    "author_uid": "string",
    "contact": t.opt("string"),
    "urls": t.opt(t.array("Link"))
});
exports.ArchiveFormat = t.union(t.lit('YearMonthDay'), t.lit('YearMonth'));
exports.Blog = t.iface([], {
    "title": "string",
    "url": "string",
    "root": "string",
    "description": t.opt("string"),
    "language": t.opt("string"),
    "authors": t.opt(t.array("Author")),
    "archive_format": "ArchiveFormat",
    "archive_with_slug": "boolean",
    "index_posts": t.opt("number"),
    "default_opengraph_image": t.opt("string")
});
exports.Tag = t.iface([], {
    "name": "string",
    "text": "string"
});
exports.PostStatus = t.union(t.lit('draft'), t.lit('publish'));
exports.Post = t.iface([], {
    "date": "string",
    "title": "string",
    "author_uid": "string",
    "guid": t.opt("string"),
    "content": t.opt("string"),
    "excerpt": t.opt("string"),
    "slug": t.opt("string"),
    "tags": t.opt(t.array("Tag")),
    "thumbnail_image": t.opt("string"),
    "opengraph_image": t.opt("string"),
    "previous_link": t.opt("Link"),
    "next_link": t.opt("Link"),
    "status": "PostStatus"
});
var exportedTypeSuite = {
    Link: exports.Link,
    Author: exports.Author,
    ArchiveFormat: exports.ArchiveFormat,
    Blog: exports.Blog,
    Tag: exports.Tag,
    PostStatus: exports.PostStatus,
    Post: exports.Post
};
exports["default"] = exportedTypeSuite;
